[package]
name = "mithril-gpu"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
mithril-codegen = { path = "../mithril-codegen" }
mithril-core = { path = "../mithril-core" }
mithril-front = { path = "../mithril-front" }
mithril-net = { path = "../mithril-net" }
mithril-rt = { path = "../mithril-rt" }

[dev-dependencies]
mithril-reassoc = { path = "../mithril-reassoc" }
