//! mithril-codegen: dual-mode Rust emission.
//!
//! `emit_rust(m, net)` turns a `CoreModule` (plus the compile-time reduced
//! residual `Net`) into a single, self-contained `main.rs` that depends only
//! on `mithril_rt` and implements its [`Program`] protocol:
//!
//! * **dive form** (`d_<fid>`) — Core compiled to sequential Rust. Values are
//!   Port raws (`u64`): i56 immediates inline (`Tag::Num`), constructors as
//!   cells (arity <= 2 direct, wider ctors chained), floats boxed in a cell.
//!   Self-tail-recursive functions become loops. Fuel is decremented once per
//!   call / loop iteration; on exhaustion at a point whose residue is exactly
//!   "the pending call" (function entry / loop top with a known destination)
//!   the pending call is spawned as a redex and the dive reports
//!   `Suspended`; a fuel-out deep inside a nested dive unwinds (`Err(false)`)
//!   and the top level falls back to the rule form.
//! * **rule form** (`fc_<fid>` fire arm + `x_<fid>` expansion + `sg_<k>`
//!   continuation segments) — the body is ANF-normalized so every call is a
//!   let-RHS or a tail call; fork points become waiting records (two
//!   independent adjacent calls share one pend-2 record, exactly like the
//!   bitonic spike's bsort), continuations become numbered segment rules with
//!   any extra environment spilled to a cell chain.
//! * **proven folds** (`CoreFn.fold`: WrapAdd / WrapAdd32 / TupleWrapAdd /
//!   TupleWrapAdd32) — the fold helper's CALL rule splits large ranges into a
//!   chunked binary fork (records + spawned redexes, never OS threads): leaf
//!   chunks run the dive form under fuel, the join rule is the combiner
//!   (wrapping add mod 2^56, or masked to the low 32 bits for the *32
//!   variants; elementwise over tuple accumulators).
//!
//! If the residual net has fully quiesced, the program is const-folded: the
//! emitted `main.rs` just prints the readback value.
//!
//! Rule numbering: 0 = boot (fires `main` with parent `ROOT`), `1 + fid` =
//! CALL rules, then fold join rules, then segments. Generated `main` takes
//! `argv[1]` = threads (default 1) and `argv[2]` = fuel (default 4096).
//!
//! v1 memory note: generated code never frees cells (values may be shared
//! after `Let`; the arena is sized for it). Records are engine-recycled.

mod fold;
mod rules;
mod seq;

use mithril_core::net::Net;
use mithril_front::core::{Core, CoreModule, Val};
use std::collections::BTreeSet;

/// Canonical printing of an `eval_core` value; the generated program's
/// `show` produces exactly this for the corresponding runtime value.
pub fn fmt_val(v: &Val) -> String {
    match v {
        Val::I(i) => i.to_string(),
        Val::F(x) => format!("{:?}", x),
        Val::C(c, fs) => {
            format!("C{}({})", c, fs.iter().map(fmt_val).collect::<Vec<_>>().join(", "))
        }
        Val::T(fs) => format!("({})", fs.iter().map(fmt_val).collect::<Vec<_>>().join(", ")),
    }
}

/// Emit a complete `main.rs` for the module (see module docs).
pub fn emit_rust(m: &CoreModule, net: &Net) -> String {
    // Const path: the compile-time reducer already finished the program.
    if net.redexes.is_empty() {
        if let Some(v) = mithril_net::readback(net, mithril_net::root_port()) {
            return format!(
                "// GENERATED by mithril-codegen (net quiesced at compile time).\nfn main() {{\n    println!(\"{{}}\", {:?});\n}}\n",
                fmt_val(&v)
            );
        }
    }

    let nf = m.fns.len();
    let folds: Vec<Option<fold::ParFold>> = (0..nf).map(|f| fold::par_fold(m, f as u32)).collect();
    let mut join_rule: Vec<u16> = vec![0; nf];
    let mut next: u16 = (1 + nf) as u16;
    for f in 0..nf {
        if folds[f].is_some() {
            join_rule[f] = next;
            next += 1;
        }
    }
    let mut sq = rules::SegQ { next, q: Vec::new() };

    let mut fns_code = String::new();
    for fid in 0..nf {
        let f = &m.fns[fid];
        let mut c = max_var(&f.body).max(f.arity as u32) + 1;
        let body = rules::normalize(&f.body, &mut c);
        fns_code.push_str(&seq::dive_fn(m, fid as u32, &body));
        fns_code.push_str(&rules::expand_fn(m, fid as u32, &body, &mut sq));
        fns_code.push_str(&call_fn(m, fid as u32, folds[fid].as_ref(), join_rule[fid]));
        if let Some(pf) = &folds[fid] {
            fns_code.push_str(&fold::join_fn(fid as u32, pf));
        }
    }
    // Segments may enqueue further segments while being emitted.
    let mut done = 0;
    while done < sq.q.len() {
        let seg = sq.q[done].clone();
        done += 1;
        fns_code.push_str(&rules::segment_fn(m, &seg, &mut sq));
    }

    let n_rules = sq.next as usize;
    let mut fire_arms = String::new();
    fire_arms.push_str(&format!(
        "            0 => fc_{}(ctx, Redex {{ a: e.a, b: e.b, aux: ROOT }}),\n",
        m.main
    ));
    for fid in 0..nf {
        fire_arms.push_str(&format!("            {} => fc_{}(ctx, e),\n", 1 + fid, fid));
    }
    for fid in 0..nf {
        if folds[fid].is_some() {
            fire_arms.push_str(&format!("            {} => jn_{}(ctx, e),\n", join_rule[fid], fid));
        }
    }
    for seg in &sq.q {
        fire_arms.push_str(&format!("            {} => sg_{}(ctx, e),\n", seg.id, seg.id));
    }
    let mut dive_arms = String::new();
    let mut exp_arms = String::new();
    for fid in 0..nf {
        let ar = m.fns[fid].arity;
        let args: String = (0..ar).map(|i| format!(", args[{}]", i + 1)).collect();
        dive_arms.push_str(&format!("            {fid} => d_{fid}(ctx, fuel, parent{args}),\n"));
        exp_arms.push_str(&format!("                    {fid} => x_{fid}(ctx, parent{args}),\n"));
    }

    let mut out = String::with_capacity(fns_code.len() + 8192);
    out.push_str(PRELUDE);
    out.push_str(&fns_code);
    out.push_str(&format!(
        "struct Pg {{ fuel: u32 }}

impl Program for Pg {{
    fn n_rules(&self) -> usize {{ {n_rules} }}
    fn rule_cost(&self, rule: u16) -> u32 {{
        // A CALL entry may burn a whole dive budget; joins/segments are tiny.
        if (1..={nf}).contains(&(rule as usize)) {{ self.fuel }} else {{ 8 }}
    }}
    fn fire(&self, rule: u16, e: Redex, ctx: &mut Wctx) {{
        match rule {{
{fire_arms}            _ => unreachable!(\"rule {{}}\", rule),
        }}
    }}
    fn dive(&self, f: u16, args: &[u64], fuel: &mut i64, ctx: &mut Wctx) -> DiveResult {{
        // args[0] is the destination; on unwind fall back to the rule form.
        let parent = args[0];
        let r = match f as usize {{
{dive_arms}            _ => unreachable!(\"dive {{}}\", f),
        }};
        match r {{
            Ok(v) => DiveResult::Done(v),
            Err(true) => DiveResult::Suspended,
            Err(false) => {{
                match f as usize {{
{exp_arms}                    _ => unreachable!(),
                }}
                DiveResult::Suspended
            }}
        }}
    }}
}}
"
    ));
    out.push_str(MAIN);
    out
}

/// The per-function CALL-rule fire arm: unpack, (par-fold split), dive.
fn call_fn(m: &CoreModule, fid: u32, pf: Option<&fold::ParFold>, jr: u16) -> String {
    let ar = m.fns[fid as usize].arity;
    let mut s = format!("fn fc_{fid}(ctx: &mut Wctx, e: Redex) {{\nlet parent = e.aux;\n");
    match ar {
        0 => {}
        1 => s.push_str("let v0 = e.a;\n"),
        2 => s.push_str("let v0 = e.a;\nlet v1 = e.b;\n"),
        _ => {
            s.push_str("let v0 = e.a;\nlet mut ch = e.b;\n");
            for i in 1..ar {
                s.push_str(&format!(
                    "let v{i} = {{ let c = ctx.cell((ch - 1) as u32); ch = c[1]; c[0] }};\n"
                ));
            }
        }
    }
    if let Some(pf) = pf {
        s.push_str(&fold::split_snippet(fid, ar, pf, jr));
    }
    let args: String = (0..ar).map(|i| format!(", v{i}")).collect();
    s.push_str(&format!(
        "match ctx.dive({fid}u16, &[parent{args}]) {{\nDiveResult::Done(v) => ctx.deliver(parent, v),\nDiveResult::Suspended => {{}}\n}}\n}}\n\n"
    ));
    s
}

// ---- Core walkers shared by the emitters ----

pub(crate) fn has_call(e: &Core) -> bool {
    match e {
        Core::Num(_) | Core::Flo(_) | Core::Var(_) => false,
        Core::Call(..) => true,
        Core::Op2(_, a, b) | Core::Cmp(_, a, b) => has_call(a) || has_call(b),
        Core::If(a, b, c) => has_call(a) || has_call(b) || has_call(c),
        Core::Let(_, r, b) => has_call(r) || has_call(b),
        Core::Ctor(_, xs) | Core::Tuple(xs) => xs.iter().any(has_call),
        Core::Match(s, arms) => has_call(s) || arms.iter().any(|(_, _, b)| has_call(b)),
        Core::Proj(a, _) => has_call(a),
    }
}

pub(crate) fn max_var(e: &Core) -> u32 {
    fn go(e: &Core, m: &mut u32) {
        match e {
            Core::Var(i) => *m = (*m).max(*i),
            Core::Num(_) | Core::Flo(_) => {}
            Core::Op2(_, a, b) | Core::Cmp(_, a, b) => {
                go(a, m);
                go(b, m);
            }
            Core::If(a, b, c) => {
                go(a, m);
                go(b, m);
                go(c, m);
            }
            Core::Let(x, r, b) => {
                *m = (*m).max(*x);
                go(r, m);
                go(b, m);
            }
            Core::Call(_, xs) | Core::Ctor(_, xs) | Core::Tuple(xs) => {
                xs.iter().for_each(|x| go(x, m))
            }
            Core::Match(s, arms) => {
                go(s, m);
                for (_, bs, b) in arms {
                    for bv in bs {
                        *m = (*m).max(*bv);
                    }
                    go(b, m);
                }
            }
            Core::Proj(a, _) => go(a, m),
        }
    }
    let mut m = 0;
    go(e, &mut m);
    m
}

pub(crate) fn free_vars(e: &Core) -> BTreeSet<u32> {
    fn go(e: &Core, bound: &mut Vec<u32>, out: &mut BTreeSet<u32>) {
        match e {
            Core::Num(_) | Core::Flo(_) => {}
            Core::Var(i) => {
                if !bound.contains(i) {
                    out.insert(*i);
                }
            }
            Core::Op2(_, a, b) | Core::Cmp(_, a, b) => {
                go(a, bound, out);
                go(b, bound, out);
            }
            Core::If(a, b, c) => {
                go(a, bound, out);
                go(b, bound, out);
                go(c, bound, out);
            }
            Core::Let(x, r, b) => {
                go(r, bound, out);
                bound.push(*x);
                go(b, bound, out);
                bound.pop();
            }
            Core::Call(_, xs) | Core::Ctor(_, xs) | Core::Tuple(xs) => {
                for x in xs {
                    go(x, bound, out);
                }
            }
            Core::Match(s, arms) => {
                go(s, bound, out);
                for (_, bs, b) in arms {
                    let n = bound.len();
                    bound.extend(bs.iter().copied());
                    go(b, bound, out);
                    bound.truncate(n);
                }
            }
            Core::Proj(a, _) => go(a, bound, out),
        }
    }
    let mut out = BTreeSet::new();
    go(e, &mut Vec::new(), &mut out);
    out
}

// ---- generated-program templates ----

const PRELUDE: &str = r#"// GENERATED by mithril-codegen. Do not edit.
#![allow(unused, unused_mut, unreachable_code, unreachable_patterns, non_snake_case, clippy::all)]
use mithril_rt::{DiveResult, Engine, Program, Redex, Wctx, ROOT};

/// Dive result: Ok(value) | Err(true) = suspended, residue already spawned |
/// Err(false) = fuel out with no spawnable destination (caller unwinds).
type R = Result<u64, bool>;

/// "No destination" sentinel for nested dives (they unwind on fuel-out).
const NONE: u64 = u64::MAX;
const M56: u64 = (1u64 << 56) - 1;
const T_NUM: u64 = 2;
const T_FLO: u64 = 3;
const T_CON: u64 = 4;

#[inline] fn tag(p: u64) -> u64 { p >> 56 }
#[inline] fn num(v: i64) -> u64 { (T_NUM << 56) | ((v as u64) & M56) }
#[inline] fn as_i(p: u64) -> i64 { ((p << 8) as i64) >> 8 }
#[inline] fn wrap56(v: i64) -> i64 { ((v as u64) << 8) as i64 >> 8 }
#[inline] fn con(addr: u32, k: u16, ar: u8) -> u64 { (T_CON << 56) | ((addr as u64) << 16) | ((k as u64) << 4) | ar as u64 }
#[inline] fn con_addr(p: u64) -> u32 { ((p >> 16) & ((1u64 << 40) - 1)) as u32 }
#[inline] fn con_tag(p: u64) -> u16 { ((p >> 4) & 0xFFF) as u16 }
#[inline] fn con_ar(p: u64) -> u8 { (p & 0xF) as u8 }
#[inline] fn flo(ctx: &mut Wctx, v: f64) -> u64 { let a = ctx.alloc(v.to_bits(), 0); (T_FLO << 56) | a as u64 }
#[inline] fn flo_val(ctx: &Wctx, p: u64) -> f64 { f64::from_bits(ctx.cell((p & M56) as u32)[0]) }

fn mith_unreachable() -> u64 { panic!("unreachable match arm reached at runtime") }

/// Constructor allocation; arity <= 2 direct, wider ctors chain cells
/// (slot 0 = field, slot 1 = continuation con carrying arity-1).
fn mk_con(ctx: &mut Wctx, k: u16, fs: &[u64]) -> u64 {
    let n = fs.len();
    if n == 0 { return con(0, k, 0); }
    if n <= 2 {
        let a = ctx.alloc(fs[0], if n == 2 { fs[1] } else { 0 });
        return con(a, k, n as u8);
    }
    let a = ctx.alloc(fs[n - 2], fs[n - 1]);
    let mut chain = con(a, k, 2);
    let mut i = n - 2;
    while i > 0 {
        i -= 1;
        let a = ctx.alloc(fs[i], chain);
        chain = con(a, k, (n - i) as u8);
    }
    chain
}

/// Field `i` of a constructor value (walks the >2-arity chain).
fn field(ctx: &Wctx, p: u64, i: usize) -> u64 {
    let (mut p, mut i) = (p, i);
    loop {
        let ar = con_ar(p) as usize;
        let c = ctx.cell(con_addr(p));
        if ar > 2 {
            if i == 0 { return c[0]; }
            p = c[1];
            i -= 1;
        } else {
            return c[i];
        }
    }
}

fn floor_div(a: i64, b: i64) -> i64 {
    let q = a.wrapping_div(b);
    let r = a.wrapping_rem(b);
    if r != 0 && (r < 0) != (b < 0) { q - 1 } else { q }
}
fn py_mod(a: i64, b: i64) -> i64 {
    let r = a.wrapping_rem(b);
    if r != 0 && (r < 0) != (b < 0) { r + b } else { r }
}

fn bin(ctx: &mut Wctx, op: u8, a: u64, b: u64) -> u64 {
    if tag(a) == T_NUM && tag(b) == T_NUM {
        let (x, y) = (as_i(a), as_i(b));
        return num(wrap56(match op {
            0 => x.wrapping_add(y),
            1 => x.wrapping_sub(y),
            2 => x.wrapping_mul(y),
            3 => x.wrapping_div(y),
            4 => floor_div(x, y),
            5 => py_mod(x, y),
            6 => x.wrapping_shl(y as u32),
            7 => x.wrapping_shr(y as u32),
            8 => x & y,
            9 => x | y,
            _ => x ^ y,
        }));
    }
    let (x, y) = (flo_val(ctx, a), flo_val(ctx, b));
    let v = match op { 0 => x + y, 1 => x - y, 2 => x * y, 3 => x / y, _ => panic!("op not defined on floats") };
    flo(ctx, v)
}

fn cmp(ctx: &Wctx, op: u8, a: u64, b: u64) -> u64 {
    let o = if tag(a) == T_NUM && tag(b) == T_NUM {
        as_i(a).partial_cmp(&as_i(b))
    } else {
        flo_val(ctx, a).partial_cmp(&flo_val(ctx, b))
    };
    let o = o.expect("incomparable values (NaN?)");
    use std::cmp::Ordering::*;
    let r = match op {
        0 => o == Less,
        1 => o != Greater,
        2 => o == Greater,
        3 => o != Less,
        4 => o == Equal,
        _ => o != Equal,
    };
    num(if r { 1 } else { 0 })
}

/// Spawn a saturated call: arity <= 2 rides in (a, b); wider calls put
/// arg0 in `a` and chain args[1..] through cells in `b` (addr+1, 0 = end).
fn spawn_call(ctx: &mut Wctx, rule: u16, args: &[u64], parent: u64) {
    let (a, b) = match args.len() {
        0 => (0, 0),
        1 => (args[0], 0),
        2 => (args[0], args[1]),
        _ => {
            let mut ch: u64 = 0;
            for &x in args[1..].iter().rev() {
                ch = ctx.alloc(x, ch) as u64 + 1;
            }
            (args[0], ch)
        }
    };
    ctx.spawn(rule, Redex { a, b, aux: parent });
}

/// n-tuple of int zeros (the identity of the additive fold combiners).
fn zeros(ctx: &mut Wctx, n: usize) -> u64 {
    let fs: Vec<u64> = (0..n).map(|_| num(0)).collect();
    mk_con(ctx, 0xFFF, &fs)
}

/// Elementwise wrapping add of two equal-shape int tuples, in place into `a`
/// (re-masked to the low 32 bits per element when `mask32`).
fn tup_add(ctx: &mut Wctx, a: u64, b: u64, mask32: bool) -> u64 {
    let (mut pa, mut pb) = (a, b);
    loop {
        let n = con_ar(pa) as usize;
        if n == 0 { return a; }
        let (ca, cb) = (con_addr(pa), con_addr(pb));
        let (xa, xb) = (ctx.cell(ca), ctx.cell(cb));
        let add = |x: u64, y: u64| {
            let v = as_i(x).wrapping_add(as_i(y));
            num(if mask32 { v & 0xFFFF_FFFF } else { wrap56(v) })
        };
        ctx.set(ca, 0, add(xa[0], xb[0]));
        if n <= 2 {
            if n == 2 { ctx.set(ca, 1, add(xa[1], xb[1])); }
            return a;
        }
        pa = xa[1];
        pb = xb[1];
    }
}

/// Post-run readback + printing of the delivered root value.
fn show(eng: &Engine, p: u64) -> String {
    match tag(p) {
        T_NUM => as_i(p).to_string(),
        T_FLO => format!("{:?}", f64::from_bits(eng.cell((p & M56) as u32)[0])),
        T_CON => {
            let k = con_tag(p);
            let mut n = con_ar(p) as usize;
            let mut q = p;
            let mut fs: Vec<String> = Vec::new();
            while n > 0 {
                let c = eng.cell(con_addr(q));
                if n <= 2 {
                    fs.push(show(eng, c[0]));
                    if n == 2 { fs.push(show(eng, c[1])); }
                    break;
                }
                fs.push(show(eng, c[0]));
                q = c[1];
                n -= 1;
            }
            if k == 0xFFF { format!("({})", fs.join(", ")) } else { format!("C{}({})", k, fs.join(", ")) }
        }
        _ => panic!("unprintable result port {:#x}", p),
    }
}

"#;

const MAIN: &str = r#"
fn main() {
    let a: Vec<String> = std::env::args().collect();
    let threads: usize = a.get(1).and_then(|s| s.parse().ok()).unwrap_or(1);
    let fuel: i64 = a.get(2).and_then(|s| s.parse().ok()).unwrap_or(4096);
    let pg = Pg { fuel: fuel.clamp(1, u32::MAX as i64) as u32 };
    let mut eng = Engine::new(threads, fuel);
    let root = eng.run(&pg, Redex { a: 0, b: 0, aux: ROOT });
    println!("{}", show(&eng, root));
}
"#;
