[package]
name = "mithril-net"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
mithril-core = { path = "../mithril-core" }
mithril-front = { path = "../mithril-front" }

[dev-dependencies]
mithril-reassoc = { path = "../mithril-reassoc" }

[[example]]
name = "compiler_planning"
path = "../../demos/compiler_planning/runtime.rs"
