#!/usr/bin/env python3
"""Render the Cornell demos as moving scenes, check parity and record FPS.

Uses the normal Mithril build/exec paths. One built program returns a vertical
strip of complete frames, amortizing process/device startup across the strip.
Pillow is needed for GIF encoding. No generated Rust or CUDA is edited.
"""
import argparse
import ast
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import statistics
import subprocess
import time

ROOT = Path(__file__).resolve().parents[1]


def animated_source(source, frames, size=None, spp=None):
    """Move both spheres in world space; pass frame through scene dependencies."""
    tree = ast.parse(source)
    functions = {f.name: f for f in tree.body if isinstance(f, ast.FunctionDef)}
    moving = {"scene"}
    while True:
        callers = {name for name, f in functions.items()
                   if any(isinstance(n, ast.Call) and isinstance(n.func, ast.Name)
                          and n.func.id in moving for n in ast.walk(f))}
        expanded = moving | callers
        if expanded == moving:
            break
        moving = expanded

    class FrameArgument(ast.NodeTransformer):
        def visit_Call(self, node):
            self.generic_visit(node)
            if isinstance(node.func, ast.Name) and node.func.id in moving:
                node.args.append(ast.Name(id="frame", ctx=ast.Load()))
            return node

    for name, f in functions.items():
        if name in moving and name != "main":
            f.args.args.append(ast.arg(arg="frame"))
        FrameArgument().visit(f)
    quarter = frames // 4
    for n in ast.walk(functions["scene"]):
        if (isinstance(n, ast.Call) and isinstance(n.func, ast.Name)
                and n.func.id == "sphere"):
            if ast.literal_eval(n.args[4]) == 5:
                center = f"(-0.48 + 0.10 * motion(frame), -0.54 + 0.06 * motion((frame + {quarter}) % {frames}), 0.15 + 0.25 * motion(frame))"
            else:
                center = f"(0.50 + 0.10 * motion((frame + {quarter}) % {frames}), -0.59 + 0.06 * motion(frame), -0.40 + 0.15 * motion((frame + {frames // 2}) % {frames}))"
            n.args[2] = ast.parse(center, mode="eval").body
    if size is not None:
        functions["size"].body = [ast.Return(value=ast.Constant(size))]
    if spp is not None and "spp" in functions:
        functions["spp"].body = [ast.Return(value=ast.Constant(spp))]
    motion = ast.parse(f"""
def motion(frame):
    t = f32(frame) / {frames}.0
    if t < 0.5:
        u = t * 2.0
        return -1.0 + 2.0 * u * u * (3.0 - 2.0 * u)
    u = (t - 0.5) * 2.0
    return 1.0 - 2.0 * u * u * (3.0 - 2.0 * u)
""").body[0]
    main = ast.parse(f"""
def main():
    n = size()
    img = array_new(n * n * {frames}, 0)
    for frame in range({frames}):
        for y in range(n):
            for x in range(n):
                img = array_set(img, (frame * n + y) * n + x, pixel(x, y, frame))
    return (n, n * {frames}, img)
""").body[0]
    tree.body = [motion] + [main if f is functions["main"] else f for f in tree.body]
    ast.fix_missing_locations(tree)
    return "# Generated by demos/render_animation.py from the Cornell demo.\n" + ast.unparse(tree) + "\n"


def image_bytes(text, frames):
    """Decode Mithril's packed RGB array, rejecting malformed image results."""
    values = [int(n) for n in re.findall(r"-?\d+", text)]
    if len(values) < 2:
        raise ValueError("missing image dimensions")
    width, height = values[:2]
    pixels = values[2:]
    if width < 1 or height != width * frames or len(pixels) != width * height:
        raise ValueError("incorrect image dimensions or pixel count")
    if any(p < 0 or p > 0xFFFFFF for p in pixels):
        raise ValueError("pixel outside packed RGB range")
    return width, bytes(c for p in pixels for c in (p >> 16, (p >> 8) & 255, p & 255))


def run(command, env):
    start = time.perf_counter()
    result = subprocess.run(command, capture_output=True, env=env, timeout=600)
    wall = time.perf_counter() - start
    if result.returncode:
        raise RuntimeError(result.stderr.decode(errors="replace")[-4000:])
    return wall, result.stdout.decode().strip(), result.stderr.decode()


def encode(rgb, width, frames, out):
    from PIL import Image
    strip = Image.frombytes("RGB", (width, width * frames), rgb)
    images = [strip.crop((0, f * width, width, (f + 1) * width)) for f in range(frames)]
    # One palette for the whole loop prevents colour changes between frames.
    palette_width = min(128, width)
    palette = strip.resize((palette_width, palette_width * frames)).quantize(colors=256)
    indexed = [im.quantize(palette=palette, dither=Image.Dither.NONE) for im in images]
    indexed[0].save(out, save_all=True, append_images=indexed[1:], duration=80,
                    loop=0, disposal=2, optimize=False)
    images[0].save(out.with_suffix(".png"))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bin", type=Path, default=ROOT / "target/release/mithril")
    parser.add_argument("--out", type=Path, default=ROOT / "target/tracer-animation")
    parser.add_argument("--frames", type=int, default=24)
    parser.add_argument("--samples", type=int, default=3)
    parser.add_argument("--size", type=int, help="override both sizes for verification")
    parser.add_argument("--spp", type=int, help="override path samples for verification")
    parser.add_argument("--oracle", action="store_true", help="check small strips against Core")
    parser.add_argument("--only", choices=["whitted", "path"])
    args = parser.parse_args()
    if args.frames < 4 or args.frames % 4 or args.samples < 1:
        parser.error("frames must be a positive multiple of four; samples must be positive")
    if args.size is not None and args.size < 1 or args.spp is not None and args.spp < 1:
        parser.error("size and spp must be positive")
    args.out.mkdir(parents=True, exist_ok=True)
    frozen = args.out / "mithril"
    shutil.copy2(args.bin, frozen)
    args.bin = frozen.resolve()
    env = dict(os.environ, CUDA_DEVICE_MAX_CONNECTIONS="1")
    for key in ("MITHRIL_STATS", "MITHRIL_GPU_STATS", "MITHRIL_GPU_TRACE", "MITHRIL_TIMING"):
        env.pop(key, None)
    report = {"date": time.strftime("%Y-%m-%d"), "frames": args.frames,
              "compiler_sha256": hashlib.sha256(args.bin.read_bytes()).hexdigest(),
              "method": "median process wall of built frame strip, after warmup; includes output and GPU context/readback; compilation and GIF encoding excluded",
              "gif_frame_ms": 80, "results": {}}
    for name in ([args.only] if args.only else ["whitted", "path"]):
        original = ROOT / f"demos/cornell_{name}.py"
        source = animated_source(original.read_text(), args.frames, args.size, args.spp)
        path = args.out / f"cornell_{name}_animated.py"
        path.write_text(source)
        cpu, gpu = args.out / f"{name}.cpu", args.out / f"{name}.gpu"
        print(f"{name}: compiling CPU and GPU", flush=True)
        for command in ([str(args.bin), "build", str(path), "-o", str(cpu)],
                        [str(args.bin), "build", "--gpu", str(path), "-o", str(gpu)]):
            run(command, env)
        lanes = {"cpu16": [str(cpu), "--threads", "16"],
                 "gpu": [str(args.bin), "exec", str(gpu)]}
        _, reference, _ = run([str(cpu), "--threads", "1"], env)
        width, rgb = image_bytes(reference, args.frames)
        digest = hashlib.sha256(rgb).hexdigest()
        if args.oracle:
            _, expected, _ = run([str(args.bin), "oracle", str(path)], env)
            if image_bytes(expected, args.frames)[1] != rgb:
                raise AssertionError(f"{name}: Core oracle mismatch")
        samples = {lane: [] for lane in lanes}
        for trial in range(-1, args.samples):
            for lane, command in lanes.items():
                wall, text, _ = run(command, env)
                w, actual = image_bytes(text, args.frames)
                if w != width or hashlib.sha256(actual).hexdigest() != digest:
                    raise AssertionError(f"{name}: {lane} frame pixels differ")
                if trial >= 0:
                    samples[lane].append(wall)
                print(f"{name}: {lane} {'warmup' if trial < 0 else trial + 1} {wall:.3f}s, pixels match", flush=True)
        entry = {"width": width, "height": width, "samples_per_pixel": args.spp or (64 if name == "path" else 4),
                 "bounce_limit": 6 if name == "path" else 5,
                 "source_sha256": hashlib.sha256(source.encode()).hexdigest(),
                 "original_sha256": hashlib.sha256(original.read_bytes()).hexdigest(),
                 "pixels_sha256": digest, "samples_s": samples,
                 "fps": {lane: args.frames / statistics.median(s) for lane, s in samples.items()},
                 "oracle_checked": args.oracle,
                 "artifacts_sha256": {lane: hashlib.sha256(p.read_bytes()).hexdigest() for lane, p in [("cpu", cpu), ("gpu", gpu)]}}
        encode(rgb, width, args.frames, args.out / f"cornell_{name}.gif")
        report["results"][name] = entry
        (args.out / "measurements.json").write_text(json.dumps(report, indent=2) + "\n")
        print(f"{name}: {entry['fps']}", flush=True)


if __name__ == "__main__":
    main()
