//! The CUDA printer of the lowered IR: `program.cu` from a `LirProgram`.
//!
//! Same decisions as the CPU program (they were made by the emitters);
//! this only spells them in C++ over the device runtime (`cuda/engine.cu`),
//! which supplies the IR's helper vocabulary without a context object.
//! Suspension results are `R` / `RA<k>` structs, tuples are `T<k>` /
//! `P2` structs, nested capture functions are lambdas, slice arguments
//! are hoisted to local arrays.

use mithril_codegen::cprint::{self, Dialect};
use mithril_codegen::lir::{FnDef, Ty, E, S};
use mithril_codegen::{LirProgram, Rule};
use mithril_net::{count_uses, ClosureSpec, Entry, MatchMeta, NExpr, ARR_PAIR};
use std::collections::{BTreeMap, HashMap, HashSet, VecDeque};
use std::fmt::Write as _;


/// Print `program.cu` for a lowered program.
pub fn print(prog: &LirProgram) -> String {
    let roots = prog.native_entries.iter().map(|fid| format!("s_{fid}")).collect::<Vec<_>>();
    let (value_entries, values) = mithril_codegen::lir::completed::entries(&prog.fns, &roots);
    let fns: Vec<_> = prog.fns.iter().chain(&values).collect();
    let functions: HashMap<_, _> = fns.iter().map(|f| (f.name.as_str(), *f)).collect();
    let fnret: HashMap<String, Ty> = fns.iter().map(|d| (d.name.clone(), d.ret)).collect();
    let mut out = String::new();
    let _ = writeln!(out, "// program.cu generated by mithril-gpu; do not edit.");
    let _ = writeln!(out, "#define PROG_NRULES {}", prog.rules.len());
    let _ = writeln!(out, "#define NFNS {}", prog.dives.len());
    let _ = writeln!(out, "#define NET_RULE {}", prog.net_rule);
    let _ = writeln!(out, "#define FILL_RULE {}", prog.fill_rule);
    let _ = writeln!(out, "#define FWD_RULE {}", prog.fwd);
    let _ = writeln!(out, "#define FIELD_RULE {}\n#define WHOLE_RULE {}\n#define RELINK_RULE {}", prog.settle_rules[0], prog.settle_rules[1], prog.settle_rules[2]);
    let _ = writeln!(out, "#define NATIVE_FRAMES {}", u8::from(prog.fns.iter().any(|f| f.name.starts_with("native_s_"))));
    let _ = writeln!(out, "#define NATIVE_ENTRIES {}", prog.native_entries.len());
    let _ = writeln!(out, "#define RANGE_FILLS {}", prog.range_fills.len());
    let _ = writeln!(out, "#include \"engine.cu\"\n");
    // tables
    let lin: Vec<&str> = prog.lin.iter().map(|b| if *b { "true" } else { "false" }).collect();
    let _ = writeln!(out, "__device__ const bool LIN[{}] = {{{}}};", prog.lin.len().max(1), if lin.is_empty() { "false".to_string() } else { lin.join(", ") });
    let _ = writeln!(out, "__device__ bool lin(u16 k) {{ return k == 0xfffu ? {} : LIN[k]; }}", prog.lin_tup);
    let cids: Vec<String> = prog.unbox_cid.iter().map(|c| c.to_string()).collect();
    let _ = writeln!(out, "__device__ const u32 UNBOX_CID[{}] = {{{}}};", prog.unbox_cid.len().max(1), if cids.is_empty() { "0".to_string() } else { cids.join(", ") });
    let _ = writeln!(out, "__device__ u32 unbox_cid(u64 slot) {{ return UNBOX_CID[slot]; }}");
    let rr: Vec<&str> = prog.rules.iter().map(|r| if matches!(r, Rule::Seg(_) | Rule::Join(_) | Rule::Hole(_) | Rule::Fill | Rule::Field | Rule::Whole | Rule::Relink) { "true" } else { "false" }).collect();
    let _ = writeln!(out, "__device__ const bool REC_RULE[PROG_NRULES] = {{{}}};\n__device__ bool prog_rec_rule(u32 rule) {{ return REC_RULE[rule]; }}", rr.join(", "));
    // rules that can fork (a call rule, a segment with a call, the net
    // region's rules): a GROW sweep fires only these
    let forks: Vec<&str> = (0..prog.rules.len()).map(|r| if prog.diving.contains(&(r as u16)) { "1" } else { "0" }).collect();
    let _ = writeln!(out, "extern \"C\" __device__ const unsigned char FORKS[PROG_NRULES] = {{{}}};\n__device__ bool prog_forks(u32 rule) {{ return FORKS[rule] != 0; }}", forks.join(", "));
    for f in &prog.folds {
        let _ = writeln!(out, "__device__ i64 FOLD_EST_{f} = 1;\n__device__ int FOLD_MEAS_{f} = 0;");
    }
    // native int tuples of every width the program uses
    out.push_str(&cprint::tuple_structs(&fns));
    out.push('\n');
    for d in &fns {
        let _ = writeln!(out, "{};", cprint::signature(d, Dialect::Cuda));
    }
    out.push('\n');
    for d in &fns {
        // C++ wants a return on every path; the IR ends with one or diverges
        out.push_str(&cprint::function(d, &fnret, Dialect::Cuda));
        out.push('\n');
    }
    // prog_dive: args[0] is the destination, the rest the arguments
    let _ = writeln!(out, "__device__ __noinline__ R prog_dive(u32 f, const u64 *args, i64 *fuel) {{\n  switch (f) {{");
    for (fid, (ar, bor)) in prog.dives.iter().enumerate() {
        let args: String = (0..*ar).map(|i| format!(", args[{}]", i + 1)).collect();
        let lent: String = (0..*ar).filter(|&i| bor[i]).map(|i| format!(" free_val(args[{}]);", i + 1)).collect();
        let _ = writeln!(out, "  case {fid}u: {{ R r = d_{fid}(fuel{args});{lent} return r; }}");
    }
    let _ = writeln!(out, "  default: g_abort(AB_UNREACHABLE); return R{{0ull, true}};\n  }}\n}}\n");
    // prog_fire: the rule table
    let _ = writeln!(out, "__device__ void prog_fire(u32 rule, u64 e0, u64 e1, u64 e2) {{\n  switch (rule) {{");
    for (id, r) in prog.rules.iter().enumerate() {
        let call = match r {
            Rule::Boot(f) => format!("fc_{f}(e0, e1, ROOT)"),
            Rule::Call(f) => format!("fc_{f}(e0, e1, e2)"),
            Rule::Join(f) => format!("jn_{f}(e0, e1, e2)"),
            Rule::Seg(k) => format!("sg_{k}(e0, e1, e2)"),
            Rule::Hole(k) => format!("hl_{k}(e0, e1, e2)"),
            Rule::Net => "net_fire(e0, e1)".to_string(),
            Rule::Fill => "fill_fire(e0, e2)".to_string(),
            Rule::Field => "field_fire(e0, e2)".to_string(),
            Rule::Whole => "whole_fire(e2)".to_string(),
            Rule::Relink => "relink_fire(e2)".to_string(),
        };
        let _ = writeln!(out, "  case {id}u: {call}; return;");
    }
    let _ = writeln!(out, "  default: g_abort(AB_UNREACHABLE); return;\n  }}\n}}");
    native_kernels(prog, &value_entries, &functions, &mut out);
    range_leaves(prog, &mut out);
    net_region(prog, &mut out);
    out
}

// Separate launches execute the same native entry selected by a populated
// work frontier. Each launch needs only its reachable runtime state.
/// The range pass's leaf: index `i` of a proven fold, through the fold's
/// own native loop over `[i, i + 1)` (engine.cu, range launches); a sum's
/// term starts from the identity 0.
fn range_leaves(prog: &LirProgram, out: &mut String) {
    if prog.range_fills.is_empty() { return; }
    let _ = writeln!(out, "__device__ i64 prog_range_leaf(u32 fid, i64 i, const u64 *ports) {{\ni64 fuel = (i64)G.fuel;\nswitch (fid) {{");
    for r in &prog.range_fills {
        let arg = |k: usize, int: bool| match (k == r.acc && r.kind != 0, int) {
            (true, _) => ", 0".to_string(),
            (false, true) => format!(", as_i(ports[{k}])"),
            (false, false) => format!(", (i64)(ports[{k}])"),
        };
        let args: String = r.ints.iter().enumerate().skip(2).map(|(k, int)| arg(k, *int)).collect();
        let _ = writeln!(out, "case {}u: return s_{}(&fuel, i, i + 1{args});", r.fid, r.fid);
    }
    let _ = writeln!(out, "default: g_abort(AB_UNREACHABLE); return 0;\n}}\n}}");
}

fn native_kernels(prog: &LirProgram, value_entries: &BTreeMap<String, String>, functions: &HashMap<&str, &FnDef>, out: &mut String) {
    if prog.native_entries.is_empty() { return; }
    let entries: Vec<String> = prog.native_entries.iter().map(|f| (1+f).to_string()).collect();
    let _=writeln!(out,"__device__ bool prog_native_rule(u32 r) {{ switch(r) {{");
    for r in &entries { let _=writeln!(out,"case {r}: return true;"); }
    let _=writeln!(out,"default: return false; }} }}");
    fn guarded(name: &str, functions: &HashMap<&str,&FnDef>, seen: &mut HashSet<String>) -> bool {
        if name=="stack_guard" { return true; }
        if !seen.insert(name.to_string()) { return false; }
        let Some(f)=functions.get(name) else { return false };
        fn calls(body: &[S], names: &mut Vec<String>) {
            for s in body {
                match s {
                    S::Fn(f) => calls(&f.body,names),
                    _ => {
                        let (e,bs)=s.parts();
                        if let Some(e)=e { e.walk(&mut |e| if let E::Call { f,.. }=e { names.push(f.clone()); }); }
                        for b in bs { calls(b,names); }
                    }
                }
            }
        }
        let mut names=Vec::new(); calls(&f.body,&mut names);
        names.iter().any(|n| guarded(n,functions,seen))
    }
    for fid in &prog.native_entries {
        let rule=1+fid;
        let original = format!("s_{fid}");
        let entry = value_entries.get(&original).unwrap_or(&original);
        let f = functions[entry.as_str()];
        let n=prog.dives[*fid as usize].0;
        let _=writeln!(out,"extern \"C\" __global__ void k_native_{rule}() {{");
        if !value_entries.contains_key(&original) { let _=writeln!(out,"s_work[threadIdx.x]=0;"); }
        let _=writeln!(out,"s_native_top[threadIdx.x]=0; s_mode[threadIdx.x]=0;");
        if guarded(&f.name,&functions,&mut HashSet::new()) { let _=writeln!(out,"s_sp0[threadIdx.x]=sp_now();"); }
        let _=writeln!(out,"const u32 begin=G.bdone[{rule}], count=g_snap[{rule}]-begin;\nfor(;;) {{\nu64 offset=native_task();\nif(offset>=count) break;\nu32 i=begin+(u32)offset;\nif (*(volatile u32*)G.abortf) break;\nconst u64 *e=&G.ebuf[((u64){rule}*G.bcap+(i&(G.bcap-1)))*3];\nu64 parent=e[2];");
        if n>2 { let _=writeln!(out,"u64 ch=e[1];"); }
        for i in 0..n {
            let value=match i { 0=>"e[0]", 1 if n==2=>"e[1]", _=>"pop_chain(&ch)" };
            let _=writeln!(out,"i64 a{i}=as_i({value});");
        }
        let args=(0..n).map(|i| format!(",a{i}")).collect::<String>();
        if value_entries.contains_key(&original) {
            let _=writeln!(out,"auto value={entry}({});", args.strip_prefix(',').unwrap_or(&args));
        } else {
            let _=writeln!(out,"i64 fuel=G.fuel;\nauto value={entry}(&fuel{args});");
        }
        match f.ret {
            Ty::I64 => { let _=writeln!(out,"deliver(parent,num(value));"); }
            Ty::Tup(k) => {
                let ports=(0..k).map(|i| format!("num(value.f{i})")).collect::<Vec<_>>().join(",");
                let _=writeln!(out,"u64 ports[{k}]={{{ports}}}; deliver(parent,mk_con(4095,ports,{k}));");
            }
            _=>unreachable!("native entry must return integers"),
        }
        let _=writeln!(out,"publish_local();\n}}\n}}");
    }
}

// ---- the net region: entries as net builders, the match tables ----

/// The instantiation of an entry (`mithril_core::lower::instantiate`)
/// spelled as straight-line C: every wire and cell a local, every
/// variable's uses fanned out by the same DUP chains.
struct Inst {
    out: String,
    tmp: u32,
    /// var -> the ports its remaining uses read, front first
    env: HashMap<u32, VecDeque<String>>,
}

impl Inst {
    fn fresh(&mut self) -> String {
        self.tmp += 1;
        format!("w{}", self.tmp)
    }
    fn stmt(&mut self, s: String) {
        self.out.push_str("  ");
        self.out.push_str(&s);
        self.out.push('\n');
    }
    fn take(&mut self, v: u32) -> String {
        self.env.get_mut(&v).and_then(|q| q.pop_front()).unwrap_or_else(|| panic!("ICE: use of var v{v} exceeds its counted uses"))
    }
    /// Bind `v` to `port` for `k` uses: 0 erases, 1 passes through, k > 1
    /// fans out through a chain of k-1 dups (one fresh label each).
    fn bind(&mut self, v: u32, port: String, k: usize) {
        match k {
            0 => self.stmt(format!("link(era(), {port});")),
            1 => self.env.entry(v).or_default().push_back(port),
            _ => {
                let outs: Vec<String> = (0..k).map(|_| self.fresh()).collect();
                for o in &outs {
                    self.stmt(format!("u64 {o} = wire();"));
                }
                let mut next = outs[k - 1].clone();
                for j in (0..k - 1).rev() {
                    let d = self.fresh();
                    self.stmt(format!("u64 {d} = dup_port(alloc_node({}, {next}), fresh_label());", outs[j]));
                    next = d;
                }
                self.stmt(format!("link({next}, {port});"));
                self.env.entry(v).or_default().extend(outs);
            }
        }
    }
    fn closure(&mut self, spec: &ClosureSpec) -> String {
        let caps: Vec<String> = spec.caps.iter().map(|v| self.take(*v)).collect();
        let l = self.list(&caps);
        format!("ref_port({l}, {})", spec.entry)
    }
    /// A list chain of `items` (a local array + `list_alloc`).
    fn list(&mut self, items: &[String]) -> String {
        let a = self.fresh();
        self.stmt(format!("u64 {a}[{}] = {{{}}};", items.len().max(1), if items.is_empty() { "0".to_string() } else { items.join(", ") }));
        let h = self.fresh();
        self.stmt(format!("u64 {h} = list_alloc({a}, {});", items.len()));
        h
    }
    /// `[p2, w]` cell fed by `p1` through an op: the result wire.
    fn binop(&mut self, code: u16, p1: String, p2: String) -> String {
        let w = self.fresh();
        self.stmt(format!("u64 {w} = wire();"));
        self.stmt(format!("link(op_port(alloc_node({p2}, {w}), {code}), {p1});"));
        w
    }
    fn inst(&mut self, e: &NExpr) -> String {
        match e {
            NExpr::Num(n) => format!("num({n}ll)"),
            NExpr::Flo(f) => format!("alloc_flo(__longlong_as_double(0x{:016x}ll))", f.to_bits()),
            NExpr::Var(v) => self.take(*v),
            NExpr::Op2(code, a, b) => {
                let p1 = self.inst(a);
                let p2 = self.inst(b);
                self.binop(*code, p1, p2)
            }
            NExpr::Let(v, r, b) => {
                let pr = self.inst(r);
                self.bind(*v, pr, count_uses(*v, b));
                self.inst(b)
            }
            NExpr::Call(f, args) => {
                let ps: Vec<String> = args.iter().map(|a| self.inst(a)).collect();
                let h = self.list(&ps);
                let w = self.fresh();
                self.stmt(format!("u64 {w} = wire();"));
                self.stmt(format!("push_redex(ref_port({h}, {f}), {w});"));
                w
            }
            NExpr::Ctor(_, args) | NExpr::Tuple(args) => {
                let ctag = if let NExpr::Ctor(t, _) = e { *t } else { 0xFFF };
                let ps: Vec<String> = args.iter().map(|a| self.inst(a)).collect();
                let a = self.fresh();
                self.stmt(format!("u64 {a}[{}] = {{{}}};", ps.len().max(1), if ps.is_empty() { "0".to_string() } else { ps.join(", ") }));
                let c = self.fresh();
                self.stmt(format!("u64 {c} = con_alloc({ctag}, {a}, {});", ps.len()));
                c
            }
            NExpr::If(c, t, e2) => {
                let pc = self.inst(c);
                let rt = self.closure(t);
                let re = self.closure(e2);
                let w = self.fresh();
                self.stmt(format!("u64 {w} = wire();"));
                self.stmt(format!("link(mkport(T_SWI, alloc_node({w}, mkport(T_EXT, alloc_node({rt}, {re})))), {pc});"));
                w
            }
            NExpr::Match(s, mid, specs) => {
                let ps = self.inst(s);
                let refs: Vec<String> = specs.iter().map(|sp| self.closure(sp)).collect();
                let h = self.list(&refs);
                let w = self.fresh();
                self.stmt(format!("u64 {w} = wire();"));
                self.stmt(format!("link(mat_port(alloc_node({w}, {h}), {mid}), {ps});"));
                w
            }
            NExpr::Proj(e2, mid) => {
                let pe = self.inst(e2);
                let w = self.fresh();
                self.stmt(format!("u64 {w} = wire();"));
                self.stmt(format!("link(mat_port(alloc_node({w}, EMPTY), {mid}), {pe});"));
                w
            }
            NExpr::Prim(code, args) => {
                let ps: Vec<String> = args.iter().map(|a| self.inst(a)).collect();
                match ps.len() {
                    1 => self.binop(*code, ps[0].clone(), "num(0ll)".into()),
                    2 => self.binop(*code, ps[0].clone(), ps[1].clone()),
                    3 => {
                        let pair = self.binop(ARR_PAIR, ps[1].clone(), ps[2].clone());
                        self.binop(*code, ps[0].clone(), pair)
                    }
                    n => panic!("ICE: builtin with {n} arguments"),
                }
            }
            NExpr::Lam(x, body) => {
                let p = self.fresh();
                let b = self.fresh();
                self.stmt(format!("u64 {p} = wire();"));
                self.stmt(format!("u64 {b} = wire();"));
                self.bind(*x, p.clone(), count_uses(*x, body));
                let o = self.inst(body);
                self.stmt(format!("link({o}, {b});"));
                format!("mkport(T_LAM, alloc_node({p}, {b}))")
            }
            NExpr::App(f, a) => {
                let pf = self.inst(f);
                let pa = self.inst(a);
                let w = self.fresh();
                self.stmt(format!("u64 {w} = wire();"));
                self.stmt(format!("link(mkport(T_APP, alloc_node({pa}, {w})), {pf});"));
                w
            }
        }
    }
}

fn entry_builder(id: usize, e: &Entry) -> String {
    let mut g = Inst { out: String::new(), tmp: 0, env: HashMap::new() };
    for (i, p) in e.params.iter().enumerate() {
        let k = count_uses(*p, &e.body);
        g.bind(*p, format!("args[{i}]"), k);
    }
    let o = g.inst(&e.body);
    g.stmt(format!("link({o}, ret);"));
    format!("// entry {id}: params {:?}\n__device__ void inst_{id}(const u64 *args, int n, u64 ret) {{\n  if (n != {}) {{ g_abort(AB_UNREACHABLE); return; }}\n{}}}\n", e.params, e.params.len(), g.out)
}

fn net_region(prog: &LirProgram, out: &mut String) {
    let np = &prog.net;
    for (i, e) in np.entries.iter().enumerate() {
        if prog.net_live[i] {
            out.push_str(&entry_builder(i, e));
        }
    }
    let _ = writeln!(out, "__device__ void prog_inst(u16 entry, const u64 *args, int n, u64 ret) {{\n  switch (entry) {{");
    for (i, _) in np.entries.iter().enumerate() {
        if prog.net_live[i] {
            let _ = writeln!(out, "  case {i}: inst_{i}(args, n, ret); return;");
        }
    }
    let _ = writeln!(out, "  default: g_abort(AB_UNREACHABLE); return;\n  }}\n}}");
    // match tables
    let _ = writeln!(out, "__device__ bool prog_mat_proj(u16 mid, usize *i) {{\n  switch (mid) {{");
    for (mid, mm) in np.metas.iter().enumerate() {
        if let MatchMeta::Proj(k) = mm {
            let _ = writeln!(out, "  case {mid}: *i = {k}; return true;");
        }
    }
    let _ = writeln!(out, "  default: return false;\n  }}\n}}");
    for (mid, mm) in np.metas.iter().enumerate() {
        if let MatchMeta::Arms(tags) = mm {
            let ts: Vec<String> = tags.iter().map(|t| t.to_string()).collect();
            let _ = writeln!(out, "__device__ const u16 MAT_{mid}[{}] = {{{}}};", tags.len().max(1), if ts.is_empty() { "0".to_string() } else { ts.join(", ") });
        }
    }
    let _ = writeln!(out, "__device__ const u16 *prog_mat_arms(u16 mid, int *n) {{\n  switch (mid) {{");
    for (mid, mm) in np.metas.iter().enumerate() {
        if let MatchMeta::Arms(tags) = mm {
            let _ = writeln!(out, "  case {mid}: *n = {}; return MAT_{mid};", tags.len());
        }
    }
    let _ = writeln!(out, "  default: *n = 0; return 0;\n  }}\n}}");
}
