//! The program-independent text of a generated program. Codegen splices
//! it verbatim around the program's own functions and tables; `{name}`
//! marks a program value it substitutes (see `mithril_codegen`).

/// Header: imports, the `Tables` impl, and the prelude helpers with the
/// program's `Tb` fixed.
pub const PRELUDE: &str = r#"// GENERATED by mithril-codegen. Do not edit.
#![allow(unused, unused_mut, unreachable_code, unreachable_patterns, non_snake_case, clippy::all)]
use mithril_rt::prelude::*;
use mithril_rt::{DiveResult, Engine, Program, Redex, Wctx, NO_REC, ROOT};
use mithril_rt::mithril_core::agents::{list_collect as net_list_collect, list_items as net_list_items, ref_entry, ref_head, wire as net_wire, Cells};
use mithril_rt::mithril_core::lower::{ClosureSpec, Entry, MatchMeta, NExpr};
use mithril_rt::mithril_core::port::{Port, Tag};
use mithril_rt::mithril_core::rules::{link as net_link, resolve as net_resolve, settle as net_settle, MatMeta, Prog};

/// The program's tables for the runtime's value helpers (`Tables`).
struct Tb;
impl Tables for Tb {
    #[inline(always)] fn lin(k: u16) -> bool { if k == 0xFFF { LIN_TUP } else { LIN[k as usize] } }
    #[inline(always)] fn unbox_cid(slot: u64) -> u32 { UNBOX_CID[slot as usize] }
    fn dup_closure(ctx: &mut Wctx, p: u64) -> u64 { dup_closure(ctx, p) }
    fn drop_closure(ctx: &mut Wctx, p: u64) {
        net_link(ctx, Port::new(Tag::Era, 0), Port(p));
        let budget = ctx.fuel();
        ctx.reduce_net(pg_ref(), budget);
    }
}
#[inline(always)] fn mk_con(ctx: &mut Wctx, k: u16, fs: &[u64]) -> u64 { mithril_rt::prelude::mk_con::<Tb>(ctx, k, fs) }
#[inline(always)] fn mk_con1(ctx: &mut Wctx, k: u16, f0: u64) -> u64 { mithril_rt::prelude::mk_con1::<Tb>(ctx, k, f0) }
#[inline(always)] fn mk_con2(ctx: &mut Wctx, k: u16, f0: u64, f1: u64) -> u64 { mithril_rt::prelude::mk_con2::<Tb>(ctx, k, f0, f1) }
#[inline(always)] fn mk_con2r(ctx: &mut Wctx, tok: u32, k: u16, f0: u64, f1: u64) -> u64 { mithril_rt::prelude::mk_con2r::<Tb>(ctx, tok, k, f0, f1) }
#[inline(always)] fn consume2k(ctx: &mut Wctx, p: u64, k: u16) -> (u64, u64) { mithril_rt::prelude::consume2k::<Tb>(ctx, p, k) }
#[inline(always)] fn consume2r(ctx: &mut Wctx, p: u64, k: u16) -> (u64, u64, u32) { mithril_rt::prelude::consume2r::<Tb>(ctx, p, k) }
#[inline(always)] fn consume_chain<const N: usize>(ctx: &mut Wctx, p: u64, k: u16) -> [u64; N] { mithril_rt::prelude::consume_chain::<Tb, N>(ctx, p, k) }
#[inline(always)] fn dup_val(ctx: &mut Wctx, p: u64) -> u64 { mithril_rt::prelude::dup_val::<Tb>(ctx, p) }
#[inline(always)] fn free_val(ctx: &mut Wctx, p: u64) { mithril_rt::prelude::free_val::<Tb>(ctx, p) }
#[inline(always)] fn take_field(ctx: &mut Wctx, p: u64, i: usize) -> u64 { mithril_rt::prelude::take_field::<Tb>(ctx, p, i) }
#[inline(always)] fn untup<const K: usize>(ctx: &mut Wctx, p: u64) -> [u64; K] { mithril_rt::prelude::untup::<Tb, K>(ctx, p) }
#[inline(always)] fn arr_new(ctx: &mut Wctx, n: i64, v: u64) -> u64 { mithril_rt::prelude::arr_new::<Tb>(ctx, n, v) }
#[inline(always)] fn arr_get(ctx: &mut Wctx, a: u64, i: i64) -> u64 { mithril_rt::prelude::arr_get::<Tb>(ctx, a, i) }
#[inline(always)] fn arr_set(ctx: &mut Wctx, a: u64, i: i64, v: u64) -> u64 { mithril_rt::prelude::arr_set::<Tb>(ctx, a, i, v) }
#[inline(always)] fn arr_set_i(ctx: &mut Wctx, a: u64, i: i64, v: u64) -> u64 { mithril_rt::prelude::arr_set_i::<Tb>(ctx, a, i, v) }
#[inline(always)] fn arr_own(ctx: &mut Wctx, a: u64) -> u64 { mithril_rt::prelude::arr_own::<Tb>(ctx, a) }
#[inline(always)] fn bin(ctx: &mut Wctx, op: u8, a: u64, b: u64, own: u8) -> u64 { mithril_rt::prelude::bin::<Tb>(ctx, op, a, b, own) }
#[inline(always)] fn cmp(ctx: &mut Wctx, op: u8, a: u64, b: u64, own: u8) -> u64 { mithril_rt::prelude::cmp::<Tb>(ctx, op, a, b, own) }
#[inline(always)] fn zeros(ctx: &mut Wctx, n: usize) -> u64 { mithril_rt::prelude::zeros::<Tb>(ctx, n) }
fn show(eng: &Engine, p: u64) -> String { mithril_rt::prelude::show::<Tb>(eng, p) }

"#;

/// The net region's rules and the closure bridge compiled code uses
/// (`{nfns}`, `{net_rule}`, `{fill_rule}`, `{field_rule}`, `{whole_rule}`,
/// `{relink_rule}`, `{fwd}`).
pub const NET_REGION: &str = r#"const NFNS: usize = {nfns};
static PG: std::sync::OnceLock<Pg> = std::sync::OnceLock::new();
fn pg_ref() -> &'static Pg { PG.get().expect("program not installed") }

impl<'e> Prog<Wctx<'e>> for Pg {
    fn unfold(&self, ctx: &mut Wctx<'e>, r: Port, other: Port) -> u64 {
        let entry = ref_entry(r) as usize;
        if entry < NFNS {
            // compiled code reads its arguments whole: a call whose
            // arguments still have pending fields waits for them, then is
            // linked again
            let peek = net_list_items(ctx, ref_head(r));
            if peek.iter().all(|a| a.tag() != Tag::Var) {
                let pending: Vec<_> = peek.iter().flat_map(|a| net_settle(ctx, *a)).collect();
                if !pending.is_empty() {
                    let j = ctx.alloc_rec({relink_rule}u16, pending.len() as u32, r.0 as u32, (r.0 >> 32) as u32, other.0);
                    await_fields(ctx, j, &pending);
                    return 1;
                }
            }
        }
        let args = net_list_collect(ctx, ref_head(r));
        if entry < NFNS && args.iter().all(|a| a.tag() != Tag::Var) {
            // a compiled function with every argument produced: its CALL
            // rule runs it (strict, native); the result comes back through
            // a FILL record that links it into `other`
            let ri = ctx.alloc_rec({fill_rule}u16, 1, other.0 as u32, (other.0 >> 32) as u32, NONE);
            let raw: Vec<u64> = args.iter().map(|p| p.0).collect();
            spawn_call(ctx, 1 + entry as u16, &raw, (ri as u64) << 3);
        } else {
            // a lifted branch/arm, or a call met before its arguments are
            // produced (inside a closure body being built): its body runs
            // as a net and waits on the wires like any agent
            assert!(entry < NET_LIVE.len() && NET_LIVE[entry], "ICE: entry {} is not shipped with the net region (ref {:#x}, other {:?})", entry, r.0, other.tag());
            ctx.instantiate(&self.entries, entry, args, other);
        }
        1
    }
    fn is_closure(&self, r: Port) -> bool {
        ref_entry(r) as usize >= NFNS
    }
    fn mat_meta(&self, mid: u16) -> MatMeta<'_> {
        match &self.metas[mid as usize] {
            MatchMeta::Proj(i) => MatMeta::Proj(*i),
            MatchMeta::Arms(tags) => MatMeta::Arms(tags),
        }
    }
    fn compute(&self, ctx: &mut Wctx<'e>, code: u16, x: Port, y: Port) -> Option<Port> {
        net_compute(ctx, code, x.0, y.0).map(Port)
    }
    fn park_op(&self, _ctx: &mut Wctx<'e>, op: Port, _y: Port) {
        panic!("runtime: builtin {} could not compute", op.payload() & 0xFF)
    }
    fn is_ext_value(&self, p: Port) -> bool {
        let t = tag(p.0);
        t >= TU || t == T_ARR
    }
    fn copy_ext(&self, ctx: &mut Wctx<'e>, p: Port) -> Port {
        Port(dup_val(ctx, p.0))
    }
    fn erase_ext(&self, ctx: &mut Wctx<'e>, p: Port) {
        free_val(ctx, p.0)
    }
    fn ext_ctor(&self, _ctx: &mut Wctx<'e>, p: Port) -> (u16, Vec<Port>) {
        let t = tag(p.0);
        assert!(t >= TU, "runtime: match on an array");
        (UNBOX_CID[(t - TU) as usize] as u16, vec![Port(num(as_i(p.0)))])
    }
    // a boxed float or constructor compiled code also holds (refcount > 1)
    fn shared(&self, ctx: &Wctx<'e>, p: Port) -> bool {
        match tag(p.0) {
            T_FLO => !ctx.rc_unique((p.0 & M56) as u32),
            T_CON => con_ar(p.0) > 0 && !lin::<Tb>(con_tag(p.0)) && !ctx.rc_unique(con_addr(p.0)),
            _ => false,
        }
    }
    fn deliver(&self, ctx: &mut Wctx<'e>, kont: Port, val: Port) {
        // compiled code reads the value whole: deliver it once settled
        let pending = net_settle(ctx, val);
        if pending.is_empty() {
            return ctx.deliver(kont.payload(), val.0);
        }
        let j = ctx.alloc_rec({whole_rule}u16, pending.len() as u32, val.0 as u32, (val.0 >> 32) as u32, kont.payload());
        await_fields(ctx, j, &pending);
    }
}

/// Builtins on runtime values (the compile-time `compute` folds the same
/// codes on literals). Codes < 16 are int/float arithmetic, 16..22
/// comparisons, 32..44 the `Prim`s, 45 the (index, value) pair of a set.
fn net_compute(ctx: &mut Wctx, code: u16, x: u64, y: u64) -> Option<u64> {
    if code >= 32 {
        return Some(match code {
            32 => num(f32_add(as_i(x), as_i(y))),
            33 => num(f32_sub(as_i(x), as_i(y))),
            34 => num(f32_mul(as_i(x), as_i(y))),
            35 => num(f32_div(as_i(x), as_i(y))),
            36 => num(f32_sqrt(as_i(x))),
            37 => num(f32_lt(as_i(x), as_i(y))),
            38 => num(f32_from_u32(as_i(x))),
            39 => num(f32_to_u32(as_i(x))),
            40 => arr_new(ctx, as_i(x), y),
            41 => arr_get(ctx, x, as_i(y)),
            42 => num(arr_len_of(x) as i64),
            43 => {
                let i = field(ctx, y, 0);
                let v = field(ctx, y, 1);
                ctx.free(con_addr(y));
                arr_set(ctx, x, as_i(i), v)
            }
            44 => num(f32_le(as_i(x), as_i(y))),
            45 => mk_con(ctx, 0xFFF, &[x, y]),
            c => unreachable!("builtin code {}", c),
        });
    }
    if is_int(x) && is_int(y) {
        let (a, b) = (take_i(x), take_i(y));
        if code >= 16 {
            let r = match code { 16 => a < b, 17 => a <= b, 18 => a > b, 19 => a >= b, 20 => a == b, 21 => a != b, _ => unreachable!() };
            return Some(num(r as i64));
        }
        if matches!(code, 3 | 4 | 5) && b == 0 {
            panic!("runtime: division by zero");
        }
        let r = match code {
            0 => a.wrapping_add(b), 1 => a.wrapping_sub(b), 2 => a.wrapping_mul(b), 3 => a.wrapping_div(b),
            4 => floor_div(a, b), 5 => py_mod(a, b), 6 => a.wrapping_shl(b as u32), 7 => a.wrapping_shr(b as u32),
            8 => a & b, 9 => a | b, 10 => a ^ b, c => unreachable!("int opcode {}", c),
        };
        return Some(num(r));
    }
    let (a, b) = (flo_val(ctx, x), flo_val(ctx, y));
    // the operands may be shared with compiled code: drop one reference each
    free_val(ctx, x);
    free_val(ctx, y);
    if code >= 16 {
        let r = match code { 16 => a < b, 17 => a <= b, 18 => a > b, 19 => a >= b, 20 => a == b, 21 => a != b, _ => unreachable!() };
        return Some(num(r as i64));
    }
    let r = match code { 0 => a + b, 1 => a - b, 2 => a * b, 3 => a / b, c => unreachable!("float opcode {}", c) };
    Some(flo(ctx, r))
}

/// Rule {net_rule}: a generic redex spilled to the engine (fuel-out, or a
/// value delivered into the net by a FILL record on another worker).
fn net_fire(ctx: &mut Wctx, e: Redex) {
    ctx.net_push(Port(e.a), Port(e.b));
    let budget = ctx.fuel();
    ctx.reduce_net(pg_ref(), budget);
}

/// A net value compiled code will read has fields still pending: one
/// {field_rule} record per field, fed by the field's wire, each reporting
/// to record `j` (which waits for all of them).
fn await_fields(ctx: &mut Wctx, j: u32, pending: &[(u32, usize, Port)]) {
    for &(cell, slot, wire) in pending {
        let f = ctx.alloc_rec({field_rule}u16, 1, cell, slot as u32, (j as u64) << 3);
        net_link(ctx, Port::new(Tag::Kont, (f as u64) << 3), wire);
    }
}

/// Rule {field_rule}: a pending field's value arrived (whole: it came
/// through a `Kont`, which settles first): written into its slot.
fn field_fire(ctx: &mut Wctx, e: Redex) {
    let inf = ctx.rec(e.aux as u32);
    Cells::set(ctx, inf.d, inf.s as usize, Port(e.a));
    ctx.deliver(inf.parent, 0);
}

/// Rule {whole_rule}: every field arrived: the value goes to its destination.
fn whole_fire(ctx: &mut Wctx, e: Redex) {
    let inf = ctx.rec(e.aux as u32);
    ctx.deliver(inf.parent, inf.d as u64 | ((inf.s as u64) << 32));
}

/// Rule {relink_rule}: a call's arguments are whole: the call meets its
/// output again (and now runs compiled).
fn relink_fire(ctx: &mut Wctx, e: Redex) {
    let inf = ctx.rec(e.aux as u32);
    // a redex, not a link: a call against a wire must unfold, not park
    ctx.net_push(Port(inf.d as u64 | ((inf.s as u64) << 32)), Port(inf.parent));
    let budget = ctx.fuel();
    ctx.reduce_net(pg_ref(), budget);
}

/// Rule {fill_rule}: a compiled call's result links into the wire (or
/// agent) the net was waiting on.
fn fill_fire(ctx: &mut Wctx, e: Redex) {
    let inf = ctx.rec(e.aux as u32);
    let target = Port(inf.d as u64 | ((inf.s as u64) << 32));
    net_link(ctx, Port(e.a), target);
    let budget = ctx.fuel();
    ctx.reduce_net(pg_ref(), budget);
}

/// Sharing a closure value from compiled code is the net's DUP–LAM rule
/// (`copy_lam`): the original cell stays the first copy, so the caller's
/// port is still that closure; the second copy is returned. The bodies
/// are copied lazily by the rules as each copy is used.
fn dup_closure(ctx: &mut Wctx, p: u64) -> u64 {
    let label = mithril_rt::mithril_core::agents::Cells::fresh_label(ctx);
    let (_, copy) = mithril_rt::mithril_core::rules::copy_lam(ctx, (p & M56) as u32, label);
    let budget = ctx.fuel();
    ctx.reduce_net(pg_ref(), budget);
    copy.0
}

/// A closure value: entry `id` instantiated over its captured values.
fn build_closure(ctx: &mut Wctx, id: u16, caps: &[u64]) -> u64 {
    let w = net_wire(ctx);
    ctx.instantiate(&pg_ref().entries, id as usize, caps.iter().map(|c| Port(*c)).collect(), w);
    let budget = ctx.fuel();
    ctx.reduce_net(pg_ref(), budget);
    let v = net_resolve(ctx, w);
    debug_assert!(v.tag() == Tag::Lam, "closure entry produced a {:?}", v.tag());
    v.0
}

/// Apply a closure value from compiled code: the application is reduced
/// in the net region; a result within budget is returned, otherwise the
/// dive suspends on a forwarding record the result will be delivered to.
fn apply(ctx: &mut Wctx, f: u64, a: u64) -> R {
    assert!(tag(f) == T_LAM, "apply: not a closure (tag {})", tag(f));
    let w = net_wire(ctx);
    let c = ctx.alloc(a, w.0);
    net_link(ctx, Port::new(Tag::App, c as u64), Port(f));
    let budget = ctx.fuel();
    ctx.reduce_net(pg_ref(), budget);
    let v = net_resolve(ctx, w);
    if v.tag() != Tag::Var {
        // compiled code reads the result whole
        let pending = net_settle(ctx, v);
        if pending.is_empty() {
            return Ok(v.0);
        }
        let j = ctx.alloc_rec({whole_rule}u16, pending.len() as u32, v.0 as u32, (v.0 >> 32) as u32, NONE);
        await_fields(ctx, j, &pending);
        return Err(j as u64);
    }
    let r = ctx.alloc_rec({fwd}u16, 1, 0, 0, NONE);
    net_link(ctx, Port::new(Tag::Kont, (r as u64) << 3), v);
    Err(r as u64)
}

/// Apply a closure value from the rule form: the result is delivered to
/// `parent` (a record slot) when the net produces it.
fn apply_spawn(ctx: &mut Wctx, f: u64, a: u64, parent: u64) {
    assert!(tag(f) == T_LAM, "apply_spawn: not a closure (tag {})", tag(f));
    let c = ctx.alloc(a, Port::new(Tag::Kont, parent).0);
    net_link(ctx, Port::new(Tag::App, c as u64), Port(f));
    let budget = ctx.fuel();
    ctx.reduce_net(pg_ref(), budget);
}

"#;

/// The `Program` impl (`{n_rules}`, `{net_rule}`, `{diving}`,
/// `{fire_arms}`, `{dive_arms}`, `{range_arms}`).
pub const PROGRAM: &str = r#"struct Pg { fuel: u32, entries: Vec<Entry>, metas: Vec<MatchMeta> }

impl Program for Pg {
    fn n_rules(&self) -> usize { {n_rules} }
    fn net_rule(&self) -> u16 { {net_rule} }
    fn rule_cost(&self, rule: u16) -> u32 {
        // An entry that may dive can burn a whole budget; pure joins are tiny.
        const DIVING: &[usize] = &[{diving}];
        if DIVING.contains(&(rule as usize)) { self.fuel } else { 8 }
    }
    fn fire(&self, rule: u16, e: Redex, ctx: &mut Wctx) {
        match rule {
{fire_arms}            _ => unreachable!("rule {}", rule),
        }
    }
    fn dive(&self, f: u16, args: &[u64], fuel: &mut i64, ctx: &mut Wctx) -> DiveResult {
        // args[0] is the destination. A suspended dive has already spawned
        // its residue behind a record chain; attach the chain's root here.
        let parent = args[0];
        let r = match f as usize {
{dive_arms}            _ => unreachable!("dive {}", f),
        };
        match r {
            Ok(v) => DiveResult::Done(v),
            Err(rec) => {
                if parent == NONE {
                    return DiveResult::Suspended(rec as u32);
                }
                ctx.set_parent(rec as u32, parent);
                DiveResult::Suspended(NO_REC)
            }
        }
    }
    #[allow(unused_variables, unreachable_code)]
    fn range_leaf(&self, fid: u32, lo: i64, hi: i64, ports: &[u64], ctx: &mut Wctx) -> i64 {
        // a native loop runs whole: its budget is never observed
        let mut fuel = i64::MAX / 2;
        match fid {
{range_arms}            _ => unreachable!("range fold {}", fid),
        }
    }
    fn release(&self, p: u64, ctx: &mut Wctx) {
        free_val(ctx, p)
    }
}
"#;

/// `main`: arguments, the engine thread, stats.
pub const MAIN: &str = r#"
fn main() {
    // threads = argv[1] (default 1), fuel = argv[2] (default 4096);
    // `--threads N` / `--fuel N` flag forms are accepted too.
    let a: Vec<String> = std::env::args().skip(1).collect();
    let mut threads: usize = 1;
    let mut fuel: i64 = -1;
    let mut pos: Vec<&str> = Vec::new();
    let mut it = a.iter();
    while let Some(w) = it.next() {
        match w.as_str() {
            "--threads" => threads = it.next().and_then(|s| s.parse().ok()).unwrap_or(threads),
            "--fuel" => fuel = it.next().and_then(|s| s.parse().ok()).unwrap_or(fuel),
            other => pos.push(other),
        }
    }
    if let Some(p) = pos.first() { if let Ok(v) = p.parse() { threads = v; } }
    if let Some(p) = pos.get(1) { if let Ok(v) = p.parse() { fuel = v; } }
    // Suspension exposes work to other workers. With one worker it only
    // bounds dive depth, so suspend rarely; the dive runs on a thread with a
    // large reserved stack so that bound stays safe.
    if fuel < 0 {
        // one worker: nothing to hand work to, so never suspend (the runner
        // thread's 1 GiB stack bounds the recursion instead)
        fuel = if threads <= 1 { 1 << 40 } else { 16384 };
    }
    let h = std::thread::Builder::new()
        .stack_size(1 << 30)
        .spawn(move || {
            let pg = Pg { fuel: fuel.clamp(1, u32::MAX as i64) as u32, entries: net_entries(), metas: net_metas() };
            let _ = PG.set(pg);
            let mut eng = Engine::new(threads, fuel);
            let root = eng.run(pg_ref(), Redex { a: 0, b: 0, aux: ROOT });
            println!("{}", show(&eng, root));
            if std::env::var_os("MITHRIL_STATS").is_some() {
                let st = eng.stats();
                eprintln!("peak_cells={} live_peak={} waves={} rewrites={} arrays_live={} bigs_live={}", st.peak_cells, st.live_peak, st.parallel_waves, st.rewrites, ARR_LIVE.load(std::sync::atomic::Ordering::Relaxed), mithril_rt::mithril_core::port::BIG_LIVE.load(std::sync::atomic::Ordering::Relaxed));
            }
        })
        .expect("spawn main runner");
    if h.join().is_err() {
        std::process::exit(101);
    }
}
"#;
